"""Application port for immutable survey history persistence."""
from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, Protocol


class StepVersioningRepository(Protocol):
    async def insert_step_version(self, step: Mapping[str, Any], version: int, actor: Mapping[str, Any] | None, change_type: str) -> dict[str, Any]: ...
    async def ensure_step_version(self, step: Mapping[str, Any], actor: Mapping[str, Any] | None = None, change_type: str = "migration") -> int: ...
    async def update_step_versioned(self, step: Mapping[str, Any], set_fields: Mapping[str, Any], unset_fields: Sequence[str] | None, actor: Mapping[str, Any], change_type: str) -> tuple[int, int, dict[str, Any]]: ...
    async def bind_revision_documents(self, revision: Mapping[str, Any]) -> int: ...
    async def write_progress_revision(self, *, user_id: str, step: Mapping[str, Any], status: str, data: Mapping[str, Any] | None, actor: Mapping[str, Any] | None, change_type: str, extra_fields: Mapping[str, Any] | None = None, unset_fields: Sequence[str] | None = None) -> dict[str, Any]: ...
    async def migrate(self) -> dict[str, int]: ...
    async def revision_view(self, user_id: str) -> list[dict[str, Any]]: ...
