"""Persistence port for step-template operations."""
from __future__ import annotations
from collections.abc import Mapping
from typing import Any, Protocol


class StepTemplateRepository(Protocol):
    async def templates(self) -> list[dict[str, Any]]: ...
    async def template(self, template_id: str) -> dict[str, Any] | None: ...
    async def insert_template(self, document: Mapping[str, Any]) -> str: ...
    async def update_template(self, template_id: str, fields: Mapping[str, Any]) -> None: ...
    async def delete_template(self, template_id: str) -> None: ...
    async def step(self, step_id: str) -> dict[str, Any] | None: ...
    async def shifted_steps(self, survey_id: str, order: int) -> list[dict[str, Any]]: ...
    async def insert_step(self, document: Mapping[str, Any]) -> tuple[str, dict[str, Any]]: ...
    async def survey_user_ids(self, survey_id: str) -> list[str]: ...
