"""Persistence boundary for survey administration."""
from __future__ import annotations
from collections.abc import Mapping
from typing import Any, Protocol

class SurveyAdministrationRepository(Protocol):
    async def surveys(self) -> list[dict[str, Any]]: ...
    async def default_survey(self) -> dict[str, Any] | None: ...
    async def survey_by_slug(self, slug: str, active_only: bool = False) -> dict[str, Any] | None: ...
    async def survey(self, survey_id: str) -> dict[str, Any] | None: ...
    async def duplicate_slug(self, slug: str, excluding_id: str | None = None) -> bool: ...
    async def clear_defaults(self, excluding_id: str | None = None) -> None: ...
    async def insert(self, document: Mapping[str, Any]) -> tuple[str, dict[str, Any]]: ...
    async def update(self, survey_id: str, fields: Mapping[str, Any]) -> None: ...
