"""Ports for administrative user management."""
from __future__ import annotations
from collections.abc import Mapping, Sequence
from typing import Any, Protocol


class AdminUserRepository(Protocol):
    async def search(self, query: Mapping[str, Any]) -> list[dict[str, Any]]: ...
    async def user(self, user_id: str) -> dict[str, Any] | None: ...
    async def user_by_email(self, email: str) -> dict[str, Any] | None: ...
    async def partner(self, partner_id: str) -> dict[str, Any] | None: ...
    async def survey(self, survey_id: str) -> dict[str, Any] | None: ...
    async def insert_user(self, document: Mapping[str, Any]) -> str: ...
    async def survey_steps(self, survey_id: str) -> list[dict[str, Any]]: ...
    async def insert_progress(self, documents: Sequence[Mapping[str, Any]]) -> None: ...
    async def link_partner(self, partner_id: str, user_id: str) -> None: ...
    async def update_user(self, user_id: str, fields: Mapping[str, Any]) -> bool: ...
    async def unlink_partners(self, user_id: str, partner_id: str | None) -> None: ...
