"""Ports used by the Stripe subscription lifecycle."""
from __future__ import annotations

from collections.abc import Awaitable, Callable, Mapping
from typing import Any, Protocol

from slices.stripe_subscription.models import PartnerSubscription, SubscriptionLink


class StripeSubscriptionGateway(Protocol):
    async def create_customer(self, email: str, name: str, partner_id: str) -> dict[str, Any]: ...
    async def create_checkout(self, customer_id: str, price_id: str, partner_id: str,
                              success_url: str, cancel_url: str, automatic_tax: bool,
                              promotion_codes: bool) -> dict[str, Any]: ...
    async def checkout_session(self, session_id: str) -> dict[str, Any]: ...
    async def create_portal(self, customer_id: str, return_url: str) -> dict[str, Any]: ...
    async def retrieve_customer(self, customer_id: str) -> dict[str, Any]: ...
    async def customers_by_email(self, email: str) -> list[dict[str, Any]]: ...
    async def retrieve_subscription(self, subscription_id: str) -> dict[str, Any]: ...
    async def subscriptions_for_customer(self, customer_id: str) -> list[dict[str, Any]]: ...


class StripeSubscriptionRepository(Protocol):
    async def user_email(self, partner: PartnerSubscription) -> str | None: ...
    async def save_customer(self, partner_id: str, customer_id: str) -> None: ...
    async def save_link(self, partner_id: str, link: SubscriptionLink, timestamp: str, repaired: bool = False) -> None: ...


UsageSynchronizer = Callable[[str], Awaitable[int]]
