"""Identity persistence ports."""
from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, Protocol


class IdentityRepository(Protocol):
    async def find_user(self, user_id: object) -> dict[str, Any] | None: ...
    async def user_by_email(self, email: str) -> dict[str, Any] | None: ...
    async def insert_user(self, document: Mapping[str, Any]) -> tuple[str, object]: ...
    async def update_user(self, user_id: object, fields: Mapping[str, Any]) -> None: ...
    async def steps(self, survey_id: str) -> list[dict[str, Any]]: ...
    async def insert_progress(self, documents: Sequence[Mapping[str, Any]]) -> None: ...
    async def insert_partner(self, document: Mapping[str, Any]) -> str: ...
    async def login_attempt(self, identifier: str) -> dict[str, Any] | None: ...
    async def record_failed_login(self, identifier: str, lockout_until: str) -> None: ...
    async def clear_login_attempt(self, identifier: str) -> None: ...
    async def consume_reset_tokens(self, user_id: str) -> None: ...
    async def insert_reset_token(self, document: Mapping[str, Any]) -> None: ...
    async def reset_token(self, token: str) -> dict[str, Any] | None: ...
    async def mark_reset_token_used(self, token: str) -> None: ...
