"""Ports for file metadata and binary object storage."""
from __future__ import annotations

from typing import Protocol

from slices.files_storage.models import StoredFile


class ObjectStorage(Protocol):
    def initialize(self) -> str: ...
    def put(self, path: str, data: bytes, content_type: str) -> int: ...
    def get(self, path: str) -> tuple[bytes, str]: ...


class FilesRepository(Protocol):
    async def insert(self, stored_file: StoredFile, created_at: str) -> None: ...
    async def find_active(self, file_id: str) -> StoredFile | None: ...
    async def user_references_file(self, user_id: str, file_id: str) -> bool: ...
    async def partner_links_user(self, partner_id: str, user_id: str) -> bool: ...
    async def partner_submission_exists(self, partner_id: str, user_id: str) -> bool: ...
    async def protect_owner_files(self, user_id: str, deleted_at: str) -> None: ...
