"""Ports required by partner administration use cases."""
from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, Protocol


class PartnerAdministrationRepository(Protocol):
    async def insert(self, document: Mapping[str, Any]) -> str: ...
    async def find(self, partner_id: str) -> dict[str, Any] | None: ...
    async def update(self, partner_id: str, fields: Mapping[str, Any]) -> dict[str, Any] | None: ...
    async def valid_survey_count(self, survey_ids: Sequence[str]) -> int: ...
    async def valid_priced_step_count(self, step_ids: Sequence[str]) -> int: ...
    async def find_user(self, user_id: str) -> dict[str, Any] | None: ...
    async def users_for_partner(self, partner_id: str) -> list[dict[str, Any]]: ...
    async def set_user_role(self, user_id: str, fields: Mapping[str, Any], remove_partner: bool) -> None: ...
    async def set_primary_user(self, partner_id: str, user_id: str | None) -> None: ...
    async def delete(self, partner_id: str) -> None: ...
