"""Ports used by persistent event processing."""
from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, Protocol

from slices.email_notifications.models import DeliveryResult, RenderedNotification
from slices.event_system.models import EventOutcome, EventPage


class EventRepository(Protocol):
    async def ensure_configs(self, defaults: Mapping[str, Mapping[str, Any]], timestamp: str) -> None: ...
    async def event(self, event_id: str) -> dict[str, Any] | None: ...
    async def config(self, event_type: str) -> dict[str, Any] | None: ...
    async def insert_event(self, event: Mapping[str, Any]) -> None: ...
    async def finish_event(self, event_id: str, outcome: EventOutcome, timestamp: str) -> None: ...
    async def skip_event(self, event_id: str, timestamp: str) -> None: ...
    async def prepare_retry(self, event_id: str) -> bool: ...
    async def enqueue_notification(self, document: Mapping[str, Any]) -> None: ...
    async def configs(self) -> list[dict[str, Any]]: ...
    async def update_config(self, event_type: str, fields: Mapping[str, Any]) -> dict[str, Any] | None: ...
    async def events(self, query: Mapping[str, Any], limit: int, skip: int) -> EventPage: ...


class EventNotifier(Protocol):
    async def email(self, recipient: str, template_key: str, variables: Mapping[str, Any]) -> DeliveryResult: ...
    async def notification(self, template_key: str, variables: Mapping[str, Any]) -> RenderedNotification | None: ...
