import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Nav
    nav_home: 'Home',
    nav_about: 'About Us',
    nav_partners: 'Partners',
    nav_login: 'Login',
    // Hero
    hero_overline: 'Your Partner Network',
    hero_title_default: 'Transform Your Business Journey',
    hero_subtitle_default: 'A guided experience to connect you with the right partners and accelerate your growth.',
    hero_cta_default: 'Get Started',
    hero_learn_more: 'Learn More',
    hero_stat: 'Successful Partnerships',
    // Features
    feat_onboarding_title: 'Guided Onboarding',
    feat_onboarding_desc: 'Step-by-step process to complete your profile and find the perfect partner match.',
    feat_network_title: 'Partner Network',
    feat_network_desc: 'Access our curated network of industry-leading partners across multiple sectors.',
    feat_tracking_title: 'Progress Tracking',
    feat_tracking_desc: 'Monitor your journey with real-time progress updates and status notifications.',
    // About
    about_overline: 'Who We Are',
    about_title_default: 'About Us',
    about_desc_default: 'We help businesses connect with the right partners through a streamlined onboarding process.',
    about_mission_default: 'Our mission is to simplify business partnerships and create meaningful connections.',
    // Partners section
    partners_overline: 'Our Network',
    partners_title_default: 'Our Partners',
    partners_desc_default: 'Work with industry-leading partners to achieve your goals.',
    // CTA
    cta_title: 'Ready to Start Your Journey?',
    cta_desc: 'Join hundreds of businesses that have found their perfect partners through our platform.',
    cta_btn: 'Create Your Account',
    // Footer
    footer_copy: '2026 GuidedJourney. All rights reserved.',
    // Auth
    auth_welcome_back: 'Welcome back',
    auth_sign_in_subtitle: 'Sign in to continue your journey',
    auth_email: 'Email',
    auth_password: 'Password',
    auth_forgot: 'Forgot password?',
    auth_sign_in: 'Sign In',
    auth_signing_in: 'Signing in...',
    auth_no_account: "Don't have an account?",
    auth_create_one: 'Create one',
    auth_create_account: 'Create your account',
    auth_create_subtitle: 'Start your journey with us today',
    auth_full_name: 'Full Name',
    auth_confirm_password: 'Confirm Password',
    auth_creating: 'Creating account...',
    auth_create_btn: 'Create Account',
    auth_have_account: 'Already have an account?',
    auth_sign_in_link: 'Sign in',
    auth_back_home: 'Back to Home',
    auth_back_login: 'Back to Login',
    auth_reset_title: 'Reset your password',
    auth_reset_subtitle: 'Enter your email and we\'ll send you a reset link.',
    auth_send_reset: 'Send Reset Link',
    auth_check_email: 'Check your email',
    auth_return_login: 'Return to Login',
    // Dashboard
    dash_your_progress: 'Your Progress',
    dash_complete: 'Complete',
    dash_welcome: 'Welcome',
    dash_save_progress: 'Save Progress',
    dash_complete_continue: 'Complete & Continue',
    dash_saving: 'Saving...',
    dash_confirm_selection: 'Confirm Selection & Continue',
    dash_review_info: 'Review Your Information',
    dash_finalize: 'Finalize Journey',
    dash_finalizing: 'Finalizing...',
    dash_prev_step: 'Previous Step',
    dash_completed: 'Completed',
    dash_in_progress: 'In Progress',
    dash_visit_website: 'Visit Website',
    dash_selected_partner: 'Selected Partner',
    dash_select_partner: 'Please select a partner',
    // Notification prefs
    notif_title: 'Notification Preferences',
    notif_desc: 'Choose when you receive email notifications about your progress.',
    notif_step_enter: 'Step Entry',
    notif_step_enter_desc: 'Receive email when starting a new step',
    notif_step_edit: 'Step Edit',
    notif_step_edit_desc: 'Receive email when saving progress on a step',
    notif_step_leave: 'Step Completion',
    notif_step_leave_desc: 'Receive email when completing a step',
    notif_save: 'Save Preferences',
    // Admin
    admin_label: 'Admin',
    admin_dashboard: 'Dashboard',
    admin_users: 'Users',
    admin_steps: 'Steps',
    admin_partners: 'Partners',
    admin_cms: 'CMS',
    admin_audit: 'Audit Log',
    admin_total_users: 'Total Users',
    admin_active_partners: 'Active Partners',
    admin_submissions: 'Submissions',
    admin_new_7days: 'New (7 days)',
    admin_user_dist: 'User Distribution',
    admin_regular_users: 'Regular Users',
    admin_partner_users: 'Partner Users',
    admin_admins: 'Admins',
    admin_step_completion: 'Step Completion Rates',
    admin_user_mgmt: 'User Management',
    admin_search_placeholder: 'Search by name or email...',
    admin_all_roles: 'All Roles',
    admin_export_csv: 'Export CSV',
    admin_selected: 'selected',
    admin_apply_role: 'Apply Role',
    admin_clear: 'Clear',
    admin_no_users: 'No users found',
    admin_step_mgmt: 'Step Management',
    admin_add_step: 'Add Step',
    admin_edit: 'Edit',
    admin_delete: 'Delete',
    admin_partner_mgmt: 'Partner Management',
    admin_add_partner: 'Add Partner',
    admin_link_user: 'Link User',
    admin_save_changes: 'Save Changes',
    admin_view: 'View',
    // Partner dashboard
    partner_label: 'Partner',
    partner_submissions: 'Submissions',
    partner_profile: 'Profile',
    partner_not_linked: 'Account Not Linked',
    partner_not_linked_desc: 'Your account is not yet linked to a partner organization. Please contact an administrator.',
    partner_user_submissions: 'User Submissions',
    partner_view_submissions_desc: 'View all submissions from users who selected your organization',
    partner_no_submissions: 'No submissions yet',
    partner_edit_profile: 'Edit Profile',
    // Common
    loading: 'Loading...',
    active: 'Active',
    inactive: 'Inactive',
    cancel: 'Cancel',
    save: 'Save',
    name: 'Name',
    email: 'Email',
    role: 'Role',
    status: 'Status',
    actions: 'Actions',
    joined: 'Joined',
    user: 'User',
    admin: 'Admin',
    partner: 'Partner',
    pending: 'Pending',
    completed: 'Completed',
    in_progress: 'In Progress',
  },
  de: {
    // Nav
    nav_home: 'Startseite',
    nav_about: 'Über uns',
    nav_partners: 'Partner',
    nav_login: 'Anmelden',
    // Hero
    hero_overline: 'Ihr Partner-Netzwerk',
    hero_title_default: 'Transformieren Sie Ihre Geschäftsreise',
    hero_subtitle_default: 'Ein geführtes Erlebnis, um Sie mit den richtigen Partnern zu verbinden und Ihr Wachstum zu beschleunigen.',
    hero_cta_default: 'Jetzt starten',
    hero_learn_more: 'Mehr erfahren',
    hero_stat: 'Erfolgreiche Partnerschaften',
    // Features
    feat_onboarding_title: 'Geführtes Onboarding',
    feat_onboarding_desc: 'Schritt-für-Schritt-Prozess, um Ihr Profil zu vervollständigen und den perfekten Partner zu finden.',
    feat_network_title: 'Partner-Netzwerk',
    feat_network_desc: 'Zugang zu unserem kuratierten Netzwerk branchenführender Partner in verschiedenen Sektoren.',
    feat_tracking_title: 'Fortschrittsverfolgung',
    feat_tracking_desc: 'Überwachen Sie Ihre Reise mit Echtzeit-Fortschrittsaktualisierungen und Status-Benachrichtigungen.',
    // About
    about_overline: 'Wer wir sind',
    about_title_default: 'Über uns',
    about_desc_default: 'Wir helfen Unternehmen, sich mit den richtigen Partnern durch einen optimierten Onboarding-Prozess zu verbinden.',
    about_mission_default: 'Unsere Mission ist es, Geschäftspartnerschaften zu vereinfachen und sinnvolle Verbindungen zu schaffen.',
    // Partners section
    partners_overline: 'Unser Netzwerk',
    partners_title_default: 'Unsere Partner',
    partners_desc_default: 'Arbeiten Sie mit branchenführenden Partnern zusammen, um Ihre Ziele zu erreichen.',
    // CTA
    cta_title: 'Bereit, Ihre Reise zu beginnen?',
    cta_desc: 'Schließen Sie sich Hunderten von Unternehmen an, die ihre perfekten Partner über unsere Plattform gefunden haben.',
    cta_btn: 'Konto erstellen',
    // Footer
    footer_copy: '2026 GuidedJourney. Alle Rechte vorbehalten.',
    // Auth
    auth_welcome_back: 'Willkommen zurück',
    auth_sign_in_subtitle: 'Melden Sie sich an, um Ihre Reise fortzusetzen',
    auth_email: 'E-Mail',
    auth_password: 'Passwort',
    auth_forgot: 'Passwort vergessen?',
    auth_sign_in: 'Anmelden',
    auth_signing_in: 'Anmeldung...',
    auth_no_account: 'Noch kein Konto?',
    auth_create_one: 'Erstellen',
    auth_create_account: 'Konto erstellen',
    auth_create_subtitle: 'Beginnen Sie noch heute Ihre Reise mit uns',
    auth_full_name: 'Vollständiger Name',
    auth_confirm_password: 'Passwort bestätigen',
    auth_creating: 'Konto wird erstellt...',
    auth_create_btn: 'Konto erstellen',
    auth_have_account: 'Bereits ein Konto?',
    auth_sign_in_link: 'Anmelden',
    auth_back_home: 'Zurück zur Startseite',
    auth_back_login: 'Zurück zur Anmeldung',
    auth_reset_title: 'Passwort zurücksetzen',
    auth_reset_subtitle: 'Geben Sie Ihre E-Mail ein und wir senden Ihnen einen Link zum Zurücksetzen.',
    auth_send_reset: 'Link senden',
    auth_check_email: 'Prüfen Sie Ihre E-Mail',
    auth_return_login: 'Zurück zur Anmeldung',
    // Dashboard
    dash_your_progress: 'Ihr Fortschritt',
    dash_complete: 'Abgeschlossen',
    dash_welcome: 'Willkommen',
    dash_save_progress: 'Fortschritt speichern',
    dash_complete_continue: 'Abschließen & Weiter',
    dash_saving: 'Speichern...',
    dash_confirm_selection: 'Auswahl bestätigen & Weiter',
    dash_review_info: 'Überprüfen Sie Ihre Informationen',
    dash_finalize: 'Reise abschließen',
    dash_finalizing: 'Wird abgeschlossen...',
    dash_prev_step: 'Vorheriger Schritt',
    dash_completed: 'Abgeschlossen',
    dash_in_progress: 'In Bearbeitung',
    dash_visit_website: 'Website besuchen',
    dash_selected_partner: 'Ausgewählter Partner',
    dash_select_partner: 'Bitte wählen Sie einen Partner',
    // Notification prefs
    notif_title: 'Benachrichtigungseinstellungen',
    notif_desc: 'Wählen Sie, wann Sie E-Mail-Benachrichtigungen über Ihren Fortschritt erhalten.',
    notif_step_enter: 'Schritt-Eintritt',
    notif_step_enter_desc: 'E-Mail erhalten, wenn ein neuer Schritt begonnen wird',
    notif_step_edit: 'Schritt-Bearbeitung',
    notif_step_edit_desc: 'E-Mail erhalten, wenn Fortschritt in einem Schritt gespeichert wird',
    notif_step_leave: 'Schritt-Abschluss',
    notif_step_leave_desc: 'E-Mail erhalten, wenn ein Schritt abgeschlossen wird',
    notif_save: 'Einstellungen speichern',
    // Admin
    admin_label: 'Admin',
    admin_dashboard: 'Dashboard',
    admin_users: 'Benutzer',
    admin_steps: 'Schritte',
    admin_partners: 'Partner',
    admin_cms: 'CMS',
    admin_audit: 'Audit-Protokoll',
    admin_total_users: 'Benutzer gesamt',
    admin_active_partners: 'Aktive Partner',
    admin_submissions: 'Einreichungen',
    admin_new_7days: 'Neu (7 Tage)',
    admin_user_dist: 'Benutzerverteilung',
    admin_regular_users: 'Reguläre Benutzer',
    admin_partner_users: 'Partner-Benutzer',
    admin_admins: 'Administratoren',
    admin_step_completion: 'Schritt-Abschlussraten',
    admin_user_mgmt: 'Benutzerverwaltung',
    admin_search_placeholder: 'Nach Name oder E-Mail suchen...',
    admin_all_roles: 'Alle Rollen',
    admin_export_csv: 'CSV Export',
    admin_selected: 'ausgewählt',
    admin_apply_role: 'Rolle anwenden',
    admin_clear: 'Löschen',
    admin_no_users: 'Keine Benutzer gefunden',
    admin_step_mgmt: 'Schrittverwaltung',
    admin_add_step: 'Schritt hinzufügen',
    admin_edit: 'Bearbeiten',
    admin_delete: 'Löschen',
    admin_partner_mgmt: 'Partnerverwaltung',
    admin_add_partner: 'Partner hinzufügen',
    admin_link_user: 'Benutzer verknüpfen',
    admin_save_changes: 'Änderungen speichern',
    admin_view: 'Ansehen',
    // Partner dashboard
    partner_label: 'Partner',
    partner_submissions: 'Einreichungen',
    partner_profile: 'Profil',
    partner_not_linked: 'Konto nicht verknüpft',
    partner_not_linked_desc: 'Ihr Konto ist noch nicht mit einer Partnerorganisation verknüpft. Bitte kontaktieren Sie einen Administrator.',
    partner_user_submissions: 'Benutzer-Einreichungen',
    partner_view_submissions_desc: 'Alle Einreichungen von Benutzern anzeigen, die Ihre Organisation ausgewählt haben',
    partner_no_submissions: 'Noch keine Einreichungen',
    partner_edit_profile: 'Profil bearbeiten',
    // Common
    loading: 'Laden...',
    active: 'Aktiv',
    inactive: 'Inaktiv',
    cancel: 'Abbrechen',
    save: 'Speichern',
    name: 'Name',
    email: 'E-Mail',
    role: 'Rolle',
    status: 'Status',
    actions: 'Aktionen',
    joined: 'Beigetreten',
    user: 'Benutzer',
    admin: 'Admin',
    partner: 'Partner',
    pending: 'Ausstehend',
    completed: 'Abgeschlossen',
    in_progress: 'In Bearbeitung',
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('gj_lang') || 'en');

  useEffect(() => {
    localStorage.setItem('gj_lang', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;

  const toggleLang = () => setLang(prev => prev === 'en' ? 'de' : 'en');

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
