"""Persistence port for CMS content and global site settings."""
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Protocol


class CmsPublicSettingsRepository(Protocol):
    async def cms_sections(self) -> list[dict[str, Any]]: ...
    async def cms_section(self, section: str) -> dict[str, Any] | None: ...
    async def save_cms_section(self, section: str, fields: Mapping[str, Any]) -> None: ...
    async def settings(self) -> dict[str, Any]: ...
    async def update_settings(self, fields: Mapping[str, Any]) -> None: ...
    async def insert_settings(self, fields: Mapping[str, Any]) -> None: ...
