"""Persistence boundary for groups and permissions."""
from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, Protocol


class GroupsPermissionsRepository(Protocol):
    async def list_groups(self) -> list[dict[str, Any]]: ...
    async def find_group(self, group_id: str) -> dict[str, Any] | None: ...
    async def find_group_by_name(self, name_key: str, excluding_id: str | None = None) -> dict[str, Any] | None: ...
    async def member_count(self, group_id: str) -> int: ...
    async def insert_group(self, document: Mapping[str, Any]) -> dict[str, Any]: ...
    async def update_group(self, group_id: str, fields: Mapping[str, object]) -> dict[str, Any] | None: ...
    async def delete_group(self, group_id: str) -> None: ...
    async def compatible_group_ids(self, group_ids: Sequence[str], role: str) -> list[str]: ...
